name: Daily Schedule

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Stale:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        id: stale
        with:
          # Stale Messages
          stale-issue-message: "This issue has been marked as stale due to a lack of activity. It will automatically closed unless there is activity."
          stale-pr-message: "This PR has been marked as stale due to a lack of activity. It will automatically closed unless there is activity."

          # Run on
          any-of-labels: "is: info-needed"

          # Labls
          stale-issue-label: "is: stale"
          stale-pr-label: "is: stale"

          # Timings
          days-before-stale: 30
          days-before-close: 7

      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
