name: Interactions
on:
  pull_request:
  issues:

jobs:
  Label-PR:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  Greet:
    if: ${{ github.event.action == 'opened'}}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for your issue! As this is your first interaction, please be sure to check the CONTRIBUTING guidelines!"
          pr-message: "Thank you for your contribution! As this is your first interaction, please ensure your PR follows the CONTRIBUTING guidelines"
