name: Tests

on:
  push:
    branches: [main]
    paths: 
      - '**.ts'
      - '**.d.ts'
  pull_request:
    branches: [main]
    paths:
      - '**.ts'
      - '**.d.ts'

jobs:
  Node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependancies
        run: yarn

      - name: Run Build
        run: yarn run build
        
      - name: Run Linter
        run: yarn run lint
        
      - name: Run Jest
        run: yarn run jest
